#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Feb 24, 2022 10:44:28 AM +0200  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

# import ColourFilterAddGUI_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("480x149+650+467")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Add Colour")
        top.configure(background="#d9d9d9")

        self.top = top

        self.AddColourFilterLabel = tk.Label(self.top)
        self.AddColourFilterLabel.place(relx=0.021, rely=0.067, height=101
                , width=454)
        self.AddColourFilterLabel.configure(anchor='w')
        self.AddColourFilterLabel.configure(background="#d9d9d9")
        self.AddColourFilterLabel.configure(compound='left')
        self.AddColourFilterLabel.configure(disabledforeground="#a3a3a3")
        self.AddColourFilterLabel.configure(font="-family {David} -size 24")
        self.AddColourFilterLabel.configure(foreground="#000000")
        self.AddColourFilterLabel.configure(text='''(         ,         ,         )  Prev:''')

        self.FilterRValueEntry = tk.Entry(self.top)
        self.FilterRValueEntry.place(relx=0.063, rely=0.201, height=60
                , relwidth=0.092)
        self.FilterRValueEntry.configure(background="white")
        self.FilterRValueEntry.configure(disabledforeground="#a3a3a3")
        self.FilterRValueEntry.configure(font="TkFixedFont")
        self.FilterRValueEntry.configure(foreground="#000000")
        self.FilterRValueEntry.configure(insertbackground="black")

        self.FilterGValueEntry = tk.Entry(self.top)
        self.FilterGValueEntry.place(relx=0.208, rely=0.201, height=60
                , relwidth=0.092)
        self.FilterGValueEntry.configure(background="white")
        self.FilterGValueEntry.configure(disabledforeground="#a3a3a3")
        self.FilterGValueEntry.configure(font="TkFixedFont")
        self.FilterGValueEntry.configure(foreground="#000000")
        self.FilterGValueEntry.configure(insertbackground="black")

        self.FilterBValueEntry = tk.Entry(self.top)
        self.FilterBValueEntry.place(relx=0.354, rely=0.201, height=60
                , relwidth=0.092)
        self.FilterBValueEntry.configure(background="white")
        self.FilterBValueEntry.configure(disabledforeground="#a3a3a3")
        self.FilterBValueEntry.configure(font="TkFixedFont")
        self.FilterBValueEntry.configure(foreground="#000000")
        self.FilterBValueEntry.configure(insertbackground="black")

        self.FilterColourPreview = tk.Canvas(self.top)
        self.FilterColourPreview.place(relx=0.667, rely=0.134, relheight=0.557
                , relwidth=0.194)
        self.FilterColourPreview.configure(background="#d9d9d9")
        self.FilterColourPreview.configure(borderwidth="2")
        self.FilterColourPreview.configure(insertbackground="black")
        self.FilterColourPreview.configure(relief="ridge")
        self.FilterColourPreview.configure(selectbackground="blue")
        self.FilterColourPreview.configure(selectforeground="white")

#def start_up():
#     ColourFilterAddGUI_support.main()

if __name__ == '__main__':
    root = tk.Tk()
    t = Toplevel1(root)
    root.mainloop()



