#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Feb 17, 2022 11:26:49 AM +0200  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from GUI import LoginGUI
from GUI import connectGUI
from GUI import LobbyCreationGUI
from GUI.BaselineGUI import GUI


class Toplevel1(GUI):
    def __init__(self, top=None, params=None):
        super(Toplevel1, self).__init__()
        if params is None:
            params = []
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        top.geometry("600x450+660+210")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")

        self.top = top

        self.username = params[0].get()
        self.password = params[1].get()
        self.client = params[2]

        self.user_label = tk.Label(self.top)
        self.user_label.place(relx=0.017, rely=0.022, height=31, width=584)
        self.user_label.configure(anchor='w')
        self.user_label.configure(background="#d9d9d9")
        self.user_label.configure(compound='left')
        self.user_label.configure(disabledforeground="#a3a3a3")
        self.user_label.configure(font="-family {David} -size 18")
        self.user_label.configure(foreground="#000000")
        self.user_label.configure(text="Current User:" + self.username)
        self.widgets.append(self.user_label)

        self.disconnect_button = tk.Button(self.top)
        self.disconnect_button.place(relx=0.033, rely=0.089, height=44, width=117)
        self.disconnect_button.configure(activebackground="#ececec")
        self.disconnect_button.configure(activeforeground="#000000")
        self.disconnect_button.configure(anchor='w')
        self.disconnect_button.configure(background="#d9d9d9")
        self.disconnect_button.configure(compound='left')
        self.disconnect_button.configure(disabledforeground="#a3a3a3")
        self.disconnect_button.configure(font="-family {David} -size 18")
        self.disconnect_button.configure(foreground="#000000")
        self.disconnect_button.configure(highlightbackground="#d9d9d9")
        self.disconnect_button.configure(highlightcolor="black")
        self.disconnect_button.configure(pady="0")
        self.disconnect_button.configure(text='''Disconnect''')
        self.disconnect_button.configure(command=lambda: self.replaceGUI(LoginGUI, self.top))
        self.widgets.append(self.disconnect_button)

        self.lobby_frame = tk.Frame(self.top)
        self.lobby_frame.place(relx=0.183, rely=0.267, relheight=0.656
                               , relwidth=0.658)
        self.lobby_frame.configure(relief='groove')
        self.lobby_frame.configure(borderwidth="2")
        self.lobby_frame.configure(relief="groove")
        self.lobby_frame.configure(background="#d9d9d9")
        self.widgets.append(self.lobby_frame)

        self.connect_button = tk.Button(self.lobby_frame)
        self.connect_button.place(relx=0.025, rely=0.034, height=134, width=377)
        self.connect_button.configure(activebackground="#ececec")
        self.connect_button.configure(activeforeground="#000000")
        self.connect_button.configure(background="#d9d9d9")
        self.connect_button.configure(compound='left')
        self.connect_button.configure(disabledforeground="#a3a3a3")
        self.connect_button.configure(font="-family {David} -size 20 -weight bold")
        self.connect_button.configure(foreground="#000000")
        self.connect_button.configure(highlightbackground="#d9d9d9")
        self.connect_button.configure(highlightcolor="black")
        self.connect_button.configure(pady="0")
        self.connect_button.configure(text='''Connect to Existing Lobby''')
        self.connect_button.configure(command=lambda: self.replaceGUI(connectGUI, self.top, [self.client]))
        self.widgets.append(self.connect_button)

        self.create_button = tk.Button(self.lobby_frame)
        self.create_button.place(relx=0.025, rely=0.508, height=134, width=377)
        self.create_button.configure(activebackground="#ececec")
        self.create_button.configure(activeforeground="#000000")
        self.create_button.configure(background="#d9d9d9")
        self.create_button.configure(compound='left')
        self.create_button.configure(disabledforeground="#a3a3a3")
        self.create_button.configure(font="-family {David} -size 20 -weight bold")
        self.create_button.configure(foreground="#000000")
        self.create_button.configure(highlightbackground="#d9d9d9")
        self.create_button.configure(highlightcolor="black")
        self.create_button.configure(pady="0")
        self.create_button.configure(text='''Create New Lobby''')
        self.create_button.configure(command=lambda: self.replaceGUI(LobbyCreationGUI, self.top, [self.client]))
        self.widgets.append(self.create_button)


# def start_up():
#    LobbyGUI_support.main()

if __name__ == '__main__':
    root = tk.Tk()
    t = Toplevel1(root)
    root.mainloop()
