#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Feb 23, 2022 12:48:37 PM +0200  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk

from GUI import LobbyManagerGUI
from GUI.BaselineGUI import GUI


class Toplevel1(GUI):
    def __init__(self, top=None, params=None):
        super(Toplevel1, self).__init__()
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+660+210")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")

        self.top = top
        self.tch48 = tk.IntVar()

        self.lobbyName  = tk.StringVar()
        self.lobbySec = tk.IntVar()
        self.Client = params[0]

        self.LobbyNameLabel = tk.Label(self.top)
        self.LobbyNameLabel.place(relx=0.217, rely=0.267, height=51, width=154)
        self.LobbyNameLabel.configure(anchor='w')
        self.LobbyNameLabel.configure(background="#d9d9d9")
        self.LobbyNameLabel.configure(compound='left')
        self.LobbyNameLabel.configure(disabledforeground="#a3a3a3")
        self.LobbyNameLabel.configure(font="-family {David} -size 18")
        self.LobbyNameLabel.configure(foreground="#000000")
        self.LobbyNameLabel.configure(text='''Lobby Name:''')
        self.widgets.append(self.LobbyNameLabel)

        self.LobbyNameEntry = tk.Entry(self.top)
        self.LobbyNameEntry.place(relx=0.483, rely=0.289, height=30
                , relwidth=0.44)
        self.LobbyNameEntry.configure(background="white")
        self.LobbyNameEntry.configure(disabledforeground="#a3a3a3")
        self.LobbyNameEntry.configure(font="TkFixedFont")
        self.LobbyNameEntry.configure(foreground="#000000")
        self.LobbyNameEntry.configure(insertbackground="black")
        self.LobbyNameEntry.configure(textvariable=self.lobbyName)
        self.widgets.append(self.LobbyNameEntry)

        self.style.map('TCheckbutton',background=
            [('selected', _bgcolor), ('active', _ana2color)])
        self.PrivateOrPublic = ttk.Checkbutton(self.top)
        self.PrivateOrPublic.place(relx=0.433, rely=0.467, relwidth=0.118
                , relheight=0.0, height=41)
        self.PrivateOrPublic.configure(variable=self.tch48)
        self.PrivateOrPublic.configure(takefocus="")
        self.PrivateOrPublic.configure(text='''Private''')
        self.PrivateOrPublic.configure(compound='left')
        self.PrivateOrPublic.configure(variable=self.lobbySec)
        self.widgets.append(self.PrivateOrPublic)

        self.LobbyCreationButton = tk.Button(self.top)
        self.LobbyCreationButton.place(relx=0.333, rely=0.667, height=114
                , width=187)
        self.LobbyCreationButton.configure(activebackground="#ececec")
        self.LobbyCreationButton.configure(activeforeground="#000000")
        self.LobbyCreationButton.configure(background="#d9d9d9")
        self.LobbyCreationButton.configure(compound='left')
        self.LobbyCreationButton.configure(disabledforeground="#a3a3a3")
        self.LobbyCreationButton.configure(font="-family {David} -size 36")
        self.LobbyCreationButton.configure(foreground="#000000")
        self.LobbyCreationButton.configure(highlightbackground="#d9d9d9")
        self.LobbyCreationButton.configure(highlightcolor="black")
        self.LobbyCreationButton.configure(pady="0")
        self.LobbyCreationButton.configure(text='''Create''')
        self.LobbyCreationButton.configure(command=lambda: self.replaceGUI(LobbyManagerGUI, self.top,
                                                                           [self.lobbyName, self.lobbySec, self.Client]))
        self.widgets.append(self.LobbyCreationButton)

if __name__ == '__main__':
    root = tk.Tk()
    t = Toplevel1(root)
    root.mainloop()


