#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Feb 23, 2022 12:48:37 PM +0200  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk

from GUI import LobbyManagerGUI
from GUI.BaselineGUI import GUI


class Toplevel1(GUI):
    def __init__(self, top=None, params=None):
        super(Toplevel1, self).__init__()
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("600x450+660+210")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")

        self.top = top
        self.tch48 = tk.IntVar()

        self.lobby_name = tk.StringVar()
        self.lobby_sec = tk.IntVar()
        self.client = params[0]

        self.lobby_name_label = tk.Label(self.top)
        self.lobby_name_label.place(relx=0.217, rely=0.267, height=51, width=154)
        self.lobby_name_label.configure(anchor='w')
        self.lobby_name_label.configure(background="#d9d9d9")
        self.lobby_name_label.configure(compound='left')
        self.lobby_name_label.configure(disabledforeground="#a3a3a3")
        self.lobby_name_label.configure(font="-family {David} -size 18")
        self.lobby_name_label.configure(foreground="#000000")
        self.lobby_name_label.configure(text='''Lobby Name:''')
        self.widgets.append(self.lobby_name_label)

        self.lobby_name_entry = tk.Entry(self.top)
        self.lobby_name_entry.place(relx=0.483, rely=0.289, height=30
                                    , relwidth=0.44)
        self.lobby_name_entry.configure(background="white")
        self.lobby_name_entry.configure(disabledforeground="#a3a3a3")
        self.lobby_name_entry.configure(font="TkFixedFont")
        self.lobby_name_entry.configure(foreground="#000000")
        self.lobby_name_entry.configure(insertbackground="black")
        self.lobby_name_entry.configure(textvariable=self.lobby_name)
        self.widgets.append(self.lobby_name_entry)

        self.style.map('TCheckbutton',background=
            [('selected', _bgcolor), ('active', _ana2color)])
        self.private_or_public = ttk.Checkbutton(self.top)
        self.private_or_public.place(relx=0.433, rely=0.467, relwidth=0.118
                                     , relheight=0.0, height=41)
        self.private_or_public.configure(variable=self.tch48)
        self.private_or_public.configure(takefocus="")
        self.private_or_public.configure(text='''Private''')
        self.private_or_public.configure(compound='left')
        self.private_or_public.configure(variable=self.lobby_sec)
        self.widgets.append(self.private_or_public)

        self.lobby_creation_button = tk.Button(self.top)
        self.lobby_creation_button.place(relx=0.333, rely=0.667, height=114
                                         , width=187)
        self.lobby_creation_button.configure(activebackground="#ececec")
        self.lobby_creation_button.configure(activeforeground="#000000")
        self.lobby_creation_button.configure(background="#d9d9d9")
        self.lobby_creation_button.configure(compound='left')
        self.lobby_creation_button.configure(disabledforeground="#a3a3a3")
        self.lobby_creation_button.configure(font="-family {David} -size 36")
        self.lobby_creation_button.configure(foreground="#000000")
        self.lobby_creation_button.configure(highlightbackground="#d9d9d9")
        self.lobby_creation_button.configure(highlightcolor="black")
        self.lobby_creation_button.configure(pady="0")
        self.lobby_creation_button.configure(text='''Create''')
        self.lobby_creation_button.configure(command=lambda: self.replaceGUI(LobbyManagerGUI, self.top, [self.lobby_name,
                                                                                                         self.lobby_sec, self.client]))
        self.widgets.append(self.lobby_creation_button)

if __name__ == '__main__':
    root = tk.Tk()
    t = Toplevel1(root)
    root.mainloop()


