#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Feb 17, 2022 11:15:50 AM +0200  platform: Windows NT
import os
import sys
import tkinter as tk

import Client
import LobbyGUI
import webbrowser
from tkinter import *

# import LoginGUI_support
from GUI.BaselineGUI import GUI


class Toplevel1(GUI):
    def __init__(self, top=None, params=None):
        super(Toplevel1, self).__init__()
        if params is None:
            params = []
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        top.geometry("600x450+660+210")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")

        self.top = top

        self.username = StringVar()
        self.password = StringVar()

        self.ip = params[0]
        self.port = params[1]

        self.title = tk.Label(self.top)
        self.title.place(relx=0.283, rely=0.022, height=61, width=254)
        self.title.configure(anchor='w')
        self.title.configure(background="#d9d9d9")
        self.title.configure(compound='left')
        self.title.configure(disabledforeground="#a3a3a3")
        self.title.configure(font="-family {David} -size 20")
        self.title.configure(foreground="#000000")
        self.title.configure(text='''Please connect to User''')
        self.widgets.append(self.title)

        self.login_frame = tk.Frame(self.top)
        self.login_frame.place(relx=0.2, rely=0.222, relheight=0.589
                               , relwidth=0.592)
        self.login_frame.configure(relief='groove')
        self.login_frame.configure(borderwidth="2")
        self.login_frame.configure(relief="groove")
        self.login_frame.configure(background="#d9d9d9")
        self.widgets.append(self.login_frame)

        self.username_label = tk.Label(self.login_frame)
        self.username_label.place(relx=0.085, rely=0.038, height=69, width=114)
        self.username_label.configure(anchor='w')
        self.username_label.configure(background="#d9d9d9")
        self.username_label.configure(compound='left')
        self.username_label.configure(disabledforeground="#a3a3a3")
        self.username_label.configure(font="-family {David} -size 18")
        self.username_label.configure(foreground="#000000")
        self.username_label.configure(text='''Username:''')
        self.widgets.append(self.username_label)

        self.username_entry = tk.Entry(self.login_frame)
        self.username_entry.place(relx=0.423, rely=0.113, height=30
                                  , relwidth=0.518)
        self.username_entry.configure(background="white")
        self.username_entry.configure(disabledforeground="#a3a3a3")
        self.username_entry.configure(font="TkFixedFont")
        self.username_entry.configure(foreground="#000000")
        self.username_entry.configure(insertbackground="black")
        self.username_entry.configure(textvariable=self.username)
        self.widgets.append(self.username_entry)

        self.password_label = tk.Label(self.login_frame)
        self.password_label.place(relx=0.085, rely=0.34, height=71, width=114)
        self.password_label.configure(anchor='w')
        self.password_label.configure(background="#d9d9d9")
        self.password_label.configure(compound='left')
        self.password_label.configure(disabledforeground="#a3a3a3")
        self.password_label.configure(font="-family {David} -size 18")
        self.password_label.configure(foreground="#000000")
        self.password_label.configure(text='''Password:''')
        self.widgets.append(self.password_label)

        self.password_entry = tk.Entry(self.login_frame)
        self.password_entry.place(relx=0.423, rely=0.415, height=30
                                  , relwidth=0.518)
        self.password_entry.configure(background="white")
        self.password_entry.configure(disabledforeground="#a3a3a3")
        self.password_entry.configure(font="TkFixedFont")
        self.password_entry.configure(foreground="#000000")
        self.password_entry.configure(insertbackground="black")
        self.password_entry.configure(textvariable=self.password)
        self.password_entry.configure(show='*')
        self.widgets.append(self.password_entry)

        self.connect_button = tk.Button(self.login_frame)
        self.connect_button.place(relx=0.338, rely=0.717, height=64, width=117)
        self.connect_button.configure(activebackground="#ececec")
        self.connect_button.configure(activeforeground="#000000")
        self.connect_button.configure(background="#d9d9d9")
        self.connect_button.configure(compound='left')
        self.connect_button.configure(disabledforeground="#a3a3a3")
        self.connect_button.configure(font="-family {David} -size 20 -weight bold")
        self.connect_button.configure(foreground="#000000")
        self.connect_button.configure(highlightbackground="#d9d9d9")
        self.connect_button.configure(highlightcolor="black")
        self.connect_button.configure(pady="0")
        self.connect_button.configure(text='''Connect''')
        self.connect_button.configure(command=lambda: self.connect_to_user(self.username.get(), self.password.get(), self.ip, self.port))
        self.widgets.append(self.connect_button)

        self.breate_Button = tk.Button(self.top)
        self.breate_Button.place(relx=0.733, rely=0.911, height=34, width=147)
        self.breate_Button.configure(activebackground="#ececec")
        self.breate_Button.configure(activeforeground="#000000")
        self.breate_Button.configure(background="#d9d9d9")
        self.breate_Button.configure(compound='left')
        self.breate_Button.configure(disabledforeground="#a3a3a3")
        self.breate_Button.configure(font="-family {David} -size 15")
        self.breate_Button.configure(foreground="#000000")
        self.breate_Button.configure(highlightbackground="#d9d9d9")
        self.breate_Button.configure(highlightcolor="black")
        self.breate_Button.configure(pady="0")
        self.breate_Button.configure(text='''Create New User''')
        self.breate_Button.configure(command=lambda:
        webbrowser.open('file:///' + os.path.dirname(os.getcwd()) + '/' + 'web_start.html'))
        self.widgets.append(self.breate_Button)

    def connect_to_user(self, Username, Password, ip, port):
        ulient_User = Client.User(Username, Password, ip, port)
        print(ulient_User.success)
        if ulient_User.success:  # If the Client was created successfully
            print("Client Creation Successful, switching GUI")
            self.replaceGUI(LobbyGUI, self.top, [self.username, self.password, ulient_User])
        else:
            t = Toplevel(self.top)
            t.geometry("232x191+660+210")
            t.title("Popup")
            t.resizable(0, 0)
            Label(t, text="Invalid user!", font=('-family {David} -size 20 -weight bold')).place(x=40, y=80)
            pass


# def start_up():
#    LoginGUI_support.main()

if __name__ == '__main__':
    root = tk.Tk()
    t = Toplevel1(root)
    root.mainloop()
