#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Feb 17, 2022 12:00:48 PM +0200  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

#import UserPromptGUI_support

class Toplevel1:
    def __init__(self, username, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("339x240+807+315")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")

        self.top = top
        self.username = username
        self.confirm = 3

        self.name_label = tk.Label(self.top)
        self.name_label.place(relx=0.295, rely=0.0, height=61, width=144)
        self.name_label.configure(anchor='w')
        self.name_label.configure(background="#d9d9d9")
        self.name_label.configure(compound='left')
        self.name_label.configure(disabledforeground="#a3a3a3")
        self.name_label.configure(font="-family {David} -size 18")
        self.name_label.configure(foreground="#000000")
        self.name_label.configure(text=self.username)

        self.prompt_label = tk.Label(self.top)
        self.prompt_label.place(relx=0.177, rely=0.25, height=51, width=224)
        self.prompt_label.configure(anchor='w')
        self.prompt_label.configure(background="#d9d9d9")
        self.prompt_label.configure(compound='left')
        self.prompt_label.configure(disabledforeground="#a3a3a3")
        self.prompt_label.configure(font="-family {David} -size 18")
        self.prompt_label.configure(foreground="#000000")
        self.prompt_label.configure(text='''Wants to join, Allow?''')

        self.yes_button = tk.Button(self.top)
        self.yes_button.place(relx=0.147, rely=0.625, height=64, width=117)
        self.yes_button.configure(activebackground="#ececec")
        self.yes_button.configure(activeforeground="#000000")
        self.yes_button.configure(background="#d9d9d9")
        self.yes_button.configure(compound='left')
        self.yes_button.configure(disabledforeground="#a3a3a3")
        self.yes_button.configure(font="-family {David} -size 18")
        self.yes_button.configure(foreground="#000000")
        self.yes_button.configure(highlightbackground="#d9d9d9")
        self.yes_button.configure(highlightcolor="black")
        self.yes_button.configure(pady="0")
        self.yes_button.configure(text='''Yes''')
        self.yes_button.configure(command=lambda: self.Yes())

        self.no_button = tk.Button(self.top)
        self.no_button.place(relx=0.531, rely=0.625, height=64, width=117)
        self.no_button.configure(activebackground="#ececec")
        self.no_button.configure(activeforeground="#000000")
        self.no_button.configure(background="#d9d9d9")
        self.no_button.configure(compound='left')
        self.no_button.configure(disabledforeground="#a3a3a3")
        self.no_button.configure(font="-family {David} -size 18")
        self.no_button.configure(foreground="#000000")
        self.no_button.configure(highlightbackground="#d9d9d9")
        self.no_button.configure(highlightcolor="black")
        self.no_button.configure(pady="0")
        self.no_button.configure(text='''No''')
        self.no_button.configure(command=lambda: self.No())

    def Yes(self):
        self.confirm = 1

    def No(self):
        self.confirm = 0


#def start_up():
#    UserPromptGUI_support.main()

if __name__ == '__main__':
    root = tk.Tk()
    t = Toplevel1(root)
    root.mainloop()




