#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    Feb 17, 2022 12:00:48 PM +0200  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

#import UserPromptGUI_support

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("339x240+807+315")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Toplevel 0")
        top.configure(background="#d9d9d9")

        self.top = top

        self.NameLabel = tk.Label(self.top)
        self.NameLabel.place(relx=0.295, rely=0.0, height=61, width=144)
        self.NameLabel.configure(anchor='w')
        self.NameLabel.configure(background="#d9d9d9")
        self.NameLabel.configure(compound='left')
        self.NameLabel.configure(disabledforeground="#a3a3a3")
        self.NameLabel.configure(font="-family {David} -size 18")
        self.NameLabel.configure(foreground="#000000")
        self.NameLabel.configure(text='''Label''')

        self.PromptLabel = tk.Label(self.top)
        self.PromptLabel.place(relx=0.177, rely=0.25, height=51, width=224)
        self.PromptLabel.configure(anchor='w')
        self.PromptLabel.configure(background="#d9d9d9")
        self.PromptLabel.configure(compound='left')
        self.PromptLabel.configure(disabledforeground="#a3a3a3")
        self.PromptLabel.configure(font="-family {David} -size 18")
        self.PromptLabel.configure(foreground="#000000")
        self.PromptLabel.configure(text='''Wants to join, Allow?''')

        self.YesButton = tk.Button(self.top)
        self.YesButton.place(relx=0.147, rely=0.625, height=64, width=117)
        self.YesButton.configure(activebackground="#ececec")
        self.YesButton.configure(activeforeground="#000000")
        self.YesButton.configure(background="#d9d9d9")
        self.YesButton.configure(compound='left')
        self.YesButton.configure(disabledforeground="#a3a3a3")
        self.YesButton.configure(font="-family {David} -size 18")
        self.YesButton.configure(foreground="#000000")
        self.YesButton.configure(highlightbackground="#d9d9d9")
        self.YesButton.configure(highlightcolor="black")
        self.YesButton.configure(pady="0")
        self.YesButton.configure(text='''Yes''')

        self.NoButton = tk.Button(self.top)
        self.NoButton.place(relx=0.531, rely=0.625, height=64, width=117)
        self.NoButton.configure(activebackground="#ececec")
        self.NoButton.configure(activeforeground="#000000")
        self.NoButton.configure(background="#d9d9d9")
        self.NoButton.configure(compound='left')
        self.NoButton.configure(disabledforeground="#a3a3a3")
        self.NoButton.configure(font="-family {David} -size 18")
        self.NoButton.configure(foreground="#000000")
        self.NoButton.configure(highlightbackground="#d9d9d9")
        self.NoButton.configure(highlightcolor="black")
        self.NoButton.configure(pady="0")
        self.NoButton.configure(text='''No''')

#def start_up():
#    UserPromptGUI_support.main()

if __name__ == '__main__':
    root = tk.Tk()
    t = Toplevel1(root)
    root.mainloop()




